# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Takatukahane" #Bestiarum
#email: your-email@example.com
description: ""
author: "Dilek Dilaver"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://takatukahane.com" # the base hostname & protocol for your site, e.g. http://example.com
version: "2024-10-10"
language: "tr"
colors: 24

timezone: Europe/Rome
encoding: utf-8

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..3

# Build settings
plugins:
  - jekyll-feed

feed:
  posts_limit: 100

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

#exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock

#jekyll_admin:
#  homepage: posts
#  hidden_links:
#    - staticfiles
#    - datafiles
#    - configuration

#defaults:
#  -
#    scope:
#      path: ""
#      type: posts
#    values:
#      layout: article
#      title: "This is a title."
#      subtitle: "This is a subtitle."
#      description: "This is a meta description."
#      date: 2019-01-25 16:40:00 +0300
#      language: "en"
#      publish: "no"

defaults:
-
  scope:
    path: '_posts/en'
    type: 'posts'
  values:
    permalink: 'en/post/:title.html'
    language: en
-
  scope:
    path: '_posts/tr'
    type: 'posts'
  values:
    permalink: 'tr/gonderi/:title.html'
    language: tr
-
  scope:
    path: '_seminars/en'
    type: 'seminars'
  values:
    permalink: 'en/seminars/:title.html'
    language: en
-
  scope:
    path: '_seminars/tr'
    type: 'seminars'
  values:
    permalink: 'tr/seminerler/:title.html'
    language: tr

collections:
  seminars:
    output: true